# format = """${custom.strat}in $all${custom.task}$character"""
format = """${custom.task}$character"""
right_format = """${custom.strat}in $all"""

[character]
success_symbol = "[Λ](bold green) "
error_symbol = "[V](bold red) "
vicmd_symbol = "[➜](bold blue) "

[custom.task]
command = "task count verbose=nothing status:pending"
when = ""
symbol = " "
# description = "Count of pending Taskwarrior tasks"
style= "bold cyan"

[custom.strat]
command = "brl which"
when = ""
# description = "Which bedrock strata"
