#!/bin/sh 

mpv_controls(){
	case $1 in
		"toggle" ) echo '{"command": ["cycle", "pause"]}' | socat - /tmp/mpvsocket ;;
		"next" ) echo '{"command": ["playlist-next"]}' | socat - /tmp/mpvsocket ;;
		"prev" ) echo '{"command": ["playlist-prev"]}' | socat - /tmp/mpvsocket ;;
		"head" ) echo '{"command": ["seek", "+5", "relative", "exact"]}' | socat - /tmp/mpvsocket ;;
		"back" ) echo '{"command": ["seek", "-5", "relative", "exact"]}' | socat - /tmp/mpvsocket ;;
		"forward" ) echo '{"command": ["seek", "+60", "relative", "exact"]}' | socat - /tmp/mpvsocket ;;
		"backward" ) echo '{"command": ["seek", "-60", "relative", "exact"]}' | socat - /tmp/mpvsocket ;;
	esac
}

pgrep mpv && mpv_controls "$1"
