#!/bin/sh 

res=$(echo "360\n720\nother" | dmenu)
vid=$(xclip -o -selection clipboard)
name=$(youtube-dl --get-filename "$vid")
dir="$HOME/Videos"
path="$dir/$name"

_ytdl18() {
	youtube-dl -f 18 -o "$path" $vid &
	mpv "$path.part"
}

_ytdl22() {
	youtube-dl -f 22 -o "$path" $vid &
	mpv "$path.part"
}

_ytdlOther() {
	youtube-dl -o "$path" $vid &
	mpv "$path.part"
}

case $res in
	"360") _ytdl18 ;;
	"720") _ytdl18 ;;
	"other") _ytdlOther ;;
esac
