#!/usr/bin/env sh

# create the session
# tmux new-session -d "nnn -a -d -P M ~/Music/" -s "music"
tmux new-session -AX -s "music" -d "nnn -a -d -P M ~/Music/"

# make the music visualizer window
tmux split-window -dv "cava"

tmux attach-session -t $SESSION:1
