#!/bin/sh

choice=$(echo "Off\nReboot\nExit\nSleep\nX"  | dmenu -i -p "Power")

_sleep() {
	slock & doas zzz
}

case $choice in
	Off) doas poweroff ;;
	Reboot) doas reboot;;
	Exit) doas pkill dwm;;
	Sleep) _sleep ;;
esac
