#!/bin/sh

choice=$(echo "Off\nReboot\nExit\nSleep\nX"  | dmenu -i -p "Power")

[ $choice = "Off" ] && doas poweroff
[ $choice = "Reboot" ] && doas reboot
[ $choice = "Exit" ] && doas pkill
[ $choice = "Sleep" ] && doas zzz
