#!/bin/sh

case $2 in
	"" ) state="copied";;
	"save" ) state="saved";;
esac

fullscreen() {
	case $1 in
		"" ) maim | xclip -selection clipboard -t image/png	;;
		"save" ) maim | tee ~/Pictures/Screenshots/$(date +%s).png | xclip -selection clipboard -t image/png	;;
	esac
}

focus() {
	case $1 in
		"" ) maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png ;;
		"save" ) maim -i $(xdotool getactivewindow) | tee ~/Pictures/Screenshots/$(date +%s).png | xclip -selection clipboard -t image/png ;;
	esac
}

select() {
	case $1 in
		"" ) maim -sBu | xclip -selection clipboard -t image/png && notify-send "maim" "selected screenshot $state" ;;
		"save" ) maim -sBu | tee ~/Pictures/Screenshots/$(date +%s).png | xclip -selection clipboard -t image/png && notify-send "maim" "selected screenshot $state" ;;
	esac
}

case $1 in
	"fullscreen" ) fullscreen $2 && notify-send "maim" "full screenshot $state" ;;
	"focus" ) focus $2 && notify-send "maim" "focused screenshot $state" ;;
	"select" ) select $2 ;;
	* ) echo "Not supported" ;;
esac
